window.MMC = window.MMC || {};

Object.assign(window.MMC, {
  AI_PROVIDERS: {
    xai: {
      id: "xai",
      pickLabel: "Grok",
      label: "Grok (xAI)",
      keyHint: "Starts with xai-",
      keyPrefix: "xai-",
      keyUrl: "https://console.x.ai/",
      keyUrlLabel: "console.x.ai",
      setupNote: "A Grok subscription on X is not the same as an API key.",
      setupSteps: [
        "Open the xAI console and sign in (an X account is fine).",
        "Go to API Keys and create a new key.",
        "Copy it. It should start with xai-.",
        "Add a little prepaid credit if the console asks — the key will not work without it.",
      ],
      defaultModel: "grok-4.6",
      models: [
        { id: "grok-4.6", label: "grok-4.6 (recommended)" },
        { id: "grok-4.5", label: "grok-4.5" },
        { id: "grok-4.3", label: "grok-4.3" },
        { id: "grok-4", label: "grok-4" },
      ],
    },
    anthropic: {
      id: "anthropic",
      pickLabel: "Claude",
      label: "Claude (Anthropic)",
      keyHint: "Starts with sk-ant-",
      keyPrefix: "sk-ant-",
      keyUrl: "https://console.anthropic.com/settings/keys",
      keyUrlLabel: "console.anthropic.com",
      setupNote: "Claude.ai or Claude Pro is not an API key. You need the Anthropic developer console.",
      setupSteps: [
        "Open the Anthropic console and sign in.",
        "Open API keys and create a key.",
        "Copy it. It should start with sk-ant-.",
        "Add credits if Anthropic asks before the key will run.",
      ],
      defaultModel: "claude-sonnet-5",
      models: [
        { id: "claude-sonnet-5", label: "claude-sonnet-5 (recommended)" },
        { id: "claude-opus-4-8", label: "claude-opus-4-8" },
        { id: "claude-fable-5", label: "claude-fable-5" },
        { id: "claude-haiku-4-5", label: "claude-haiku-4-5" },
      ],
    },
    openai: {
      id: "openai",
      pickLabel: "ChatGPT",
      label: "ChatGPT (OpenAI)",
      keyHint: "Starts with sk-",
      keyPrefix: "sk-",
      keyUrl: "https://platform.openai.com/api-keys",
      keyUrlLabel: "platform.openai.com",
      setupNote: "ChatGPT Plus on chatgpt.com is not an API key. You need OpenAI’s developer platform.",
      setupSteps: [
        "Open platform.openai.com and sign in — not chatgpt.com.",
        "Open API keys and create a new secret key.",
        "Copy it immediately. OpenAI only shows it once. It should start with sk-.",
        "Add billing on the OpenAI platform if it asks.",
      ],
      defaultModel: "gpt-5.6-terra",
      models: [
        { id: "gpt-5.6-sol", label: "gpt-5.6-sol (flagship)" },
        { id: "gpt-5.6-terra", label: "gpt-5.6-terra (balanced)" },
        { id: "gpt-5.6-luna", label: "gpt-5.6-luna (fast/cheap)" },
        { id: "gpt-4o", label: "gpt-4o" },
        { id: "gpt-4o-mini", label: "gpt-4o-mini" },
      ],
    },
    gemini: {
      id: "gemini",
      pickLabel: "Gemini",
      label: "Gemini (Google)",
      keyHint: "Paste the key from Google AI Studio",
      keyPrefix: "",
      keyUrl: "https://aistudio.google.com/apikey",
      keyUrlLabel: "aistudio.google.com",
      setupNote: "The Gemini app on your phone is not an API key. Use Google AI Studio.",
      setupSteps: [
        "Open Google AI Studio and sign in with Google.",
        "Tap Get API key, then Create API key.",
        "Copy the key and come back here.",
        "If Google asks to enable the Gemini API, accept it.",
      ],
      defaultModel: "gemini-2.5-flash",
      models: [
        { id: "gemini-2.5-flash", label: "gemini-2.5-flash (recommended)" },
        { id: "gemini-2.5-pro", label: "gemini-2.5-pro" },
        { id: "gemini-2.0-flash", label: "gemini-2.0-flash" },
      ],
    },
  },
});
